package com.hospital.appointment.enums;

public enum ExecutionEventPoint {
	CREATE_APPOINTMENT_RECEIVED,
	FINANCIAL_RESULT_RECEIVED,
	RESCHEDULE_APPOINTMENT_RECEIVED,
	CANCEL_APPOINTMENT_RECEIVED,
	TREATMENT_RESULT_RECEIVED

}
